[build]
  command = "rm -rf node_modules package-lock.json && npm install && turbo run build --filter docs"
  publish = "docs/dist"

[build.environment]
  NODE_VERSION = "22"
  NPM_FLAGS = "--legacy-peer-deps"