[phases.setup]
nixPkgs = ['nodejs_22', 'npm-9_x']

[build]
env = ["DATABASE_URL"]

[phases.install]
cmds = [
  'rm -rf node_modules package-lock.json lib',
  'npm install --legacy-peer-deps',
]

[phases.build]
cmds = [
  'npm run build',
]
